apiVersion: v1
kind: Service
metadata:
  name: cozinha-nodeport
  labels:
    app: cozinha
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30082
    protocol: TCP
    name: http
  selector:
    app: cozinha
